import { build } from 'tsdown'
import { resolve } from 'pathe'
import type { Nuxt } from '@nuxt/schema'
import PluginAlias from '@rollup/plugin-alias'
import type { Alias } from '@rollup/plugin-alias'
import type { VuetifyNuxtContext } from './context'
import * as fsPromises from 'node:fs/promises'
import { generateCode } from 'magicast'
import { buildVuetifyClientHintsConfiguration, SSRClientHintsConfigurationDefinition } from './ssr-client-hints'
import { addTemplate, addTypeTemplate } from '@nuxt/kit'

export async function generateTSDownNuxtTemplates(
  nuxt: Nuxt,
  ctx: VuetifyNuxtContext,
  fromWatcher: boolean,
): Promise<void> {
  const cwd = nuxt.options.buildDir
  const buildDir = resolve(cwd, 'vuetify')
  const vuetifyOptionsFile = resolve(buildDir, 'temp-vuetify-options.ts')
  const vuetifyRulesFile = resolve(buildDir, 'temp-vuetify-rules.ts')
  const vuetifySSRFile = resolve(buildDir, 'temp-vuetify-ssr.ts')
  const entry = [
    vuetifyOptionsFile,
    ctx.enableRules ? vuetifyRulesFile : undefined,
    ctx.ssrClientHints.enabled ? vuetifySSRFile : undefined,
  ].filter(Boolean) as string[]

  await fsPromises.mkdir(buildDir, { recursive: true })

  await Promise.all([
    generateTempVuetifyOptions(vuetifyOptionsFile, ctx),
    generateTempVuetifyRules(vuetifyRulesFile, ctx),
    generateTempVuetifySSR(vuetifySSRFile, ctx),
  ])

  const entries = [...collectPluginEntries(ctx)]

  console.time('vuetify:tsdown')
  await build({
    cwd,
    tsconfig: resolve(nuxt.options.rootDir, './tsconfig.json'),
    outDir: buildDir,
    format: 'esm',
    clean: false,
    entry,
    dts: true,
    banner: `// Generated by vuetify-nuxt-module`,
    external: [
      /.*/, // everything is external
    ],
    plugins: [PluginAlias({ entries: entries.map(e => e[0]) })],
  })

  await Promise.all([
    prepareVuetifyTemplates(ctx, 'options', true, !fromWatcher, buildDir),
    prepareVuetifyTemplates(ctx, 'rules', ctx.enableRules, !fromWatcher, buildDir),
    prepareVuetifyTemplates(ctx, 'ssr', ctx.ssrClientHints.enabled, !fromWatcher, buildDir),
  ])
  console.timeEnd('vuetify:tsdown')
}

function* collectPluginEntries(ctx: VuetifyNuxtContext): Generator<[
  alias: Alias,
  external: string | RegExp,
], undefined, void> {
  for (const { local, relative, filePathWithExtension, relativePath } of ctx.imports.values()) {
    if (relative && filePathWithExtension) {
      yield [{
        find: local,
        replacement: filePathWithExtension,
      }, relativePath!] as const
    }
  }
  if (ctx.enableRules) {
    for (const { local, relative, filePathWithExtension, relativePath } of ctx.rulesConfiguration.rulesImports.values()) {
      if (relative && filePathWithExtension) {
        yield [{
          find: local,
          replacement: filePathWithExtension,
        }, relativePath!] as const
      }
    }
  }
}

const TEMPLATE_NAMES = {
  options: ['configuration.mjs', 'configuration.d.ts'],
  rules: ['rules-configuration.mjs', 'rules-configuration.d.ts'],
  ssr: ['ssr-client-hints-configuration.mjs', 'ssr-client-hints-configuration.d.ts'],
} as const

async function prepareVuetifyTemplates(
  ctx: VuetifyNuxtContext,
  templateName: 'options' | 'rules' | 'ssr',
  isEnabled: boolean,
  registerTemplate: boolean,
  vuetifyDir: string,
) {
  if (!isEnabled) {
    if (ctx.virtualModules[templateName]) {
      ctx.virtualModules[templateName] = { js: '', dts: '' }
    }
    return
  }

  const files = [
    resolve(vuetifyDir, `temp-vuetify-${templateName}.js`),
    resolve(vuetifyDir, `temp-vuetify-${templateName}.d.ts`),
  ]

  const [js, dts] = await Promise.all(files.map(file => fsPromises.readFile(file, 'utf-8')))

  ctx.virtualModules[templateName] = {
    js: js!.replace(new RegExp(`//#region .*${templateName}.ts`), '').replace('//#endregion', ''),
    dts: dts!.replace(new RegExp(`//#region .*${templateName}.d.ts`), '').replace('//#endregion', ''),
  }

  if (registerTemplate) {
    addTypeTemplate({
      filename: `vuetify/${TEMPLATE_NAMES[templateName][1]}`,
      write: true,
      getContents: () => ctx.virtualModules[templateName].dts,
    })
    addTemplate({
      filename: `vuetify/${TEMPLATE_NAMES[templateName][0]}`,
      write: true,
      getContents: () => ctx.virtualModules[templateName].js,
    })
  }

  await Promise.all([
    ...files,
    resolve(vuetifyDir, `temp-vuetify-${templateName}.ts`),
  ].map(file => fsPromises.rm(file, { force: true })))
}

async function generateTempVuetifyOptions(
  path: string,
  ctx: VuetifyNuxtContext,
) {
  await fsPromises.writeFile(
    path,
    `${ctx.configurationImports}

const vuetifyOptions = ${generateCode(ctx.vuetifyOptions).code} as const
export function vuetifyConfiguration() {
  return vuetifyOptions
}
`, { encoding: 'utf-8' },
  )
}

async function generateTempVuetifyRules(
  path: string,
  ctx: VuetifyNuxtContext,
) {
  if (!ctx.enableRules) {
    return
  }

  await fsPromises.writeFile(
    path,
    `${ctx.rulesConfiguration.imports}
const rulesOptions = ${generateCode(ctx.rulesConfiguration.rulesOptions).code} as const
export { rulesOptions }
`, { encoding: 'utf-8' },
  )
/*
  const fromLabs = ctx.rulesConfiguration.fromLabs

  await fsPromises.writeFile(
    path,
    `${ctx.rulesConfiguration.imports}
const rulesOptions = ${generateCode(ctx.rulesConfiguration.rulesOptions).code} satisfies import('vuetify/${fromLabs ? 'labs/' : ''}rules').RulesOptions
export { rulesOptions }
`, { encoding: 'utf-8' },
  )
*/
}

async function generateTempVuetifySSR(
  path: string,
  ctx: VuetifyNuxtContext,
) {
  if (!ctx.ssrClientHints.enabled) {
    return
  }

  await fsPromises.writeFile(
    path,
    `${SSRClientHintsConfigurationDefinition}
export const ssrClientHintsConfiguration = ${JSON.stringify(buildVuetifyClientHintsConfiguration(ctx))} as const
`, { encoding: 'utf-8' },
  )
}
